MVCGruppuppgift/MVCGruppuppgift/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCGruppuppgift.Models;

namespace MVCGruppuppgift.Controllers
{

    public class HomeController : Controller
    {
        tvdbEntities db = new tvdbEntities();
        //GET: Home
        public ActionResult Index(string searchString, string genreSearch)
        {
            var program = db.program.Include(p => p.channel);
            if (!String.IsNullOrEmpty(searchString))
            {
                program = program.Where(p => p.name.Contains(searchString) || p.genre.Contains(searchString) || p.channel.name.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(genreSearch))
            {
                program = program.Where(p => p.genre.Contains(genreSearch));
            }
            ViewBag.newslist = db.news.ToList();
            return View(program.ToList());
        }

        public ActionResult MyPage(person User)
        {
            var Usr = Convert.ToInt32(Session["id"]);
            if (Session["id"] != null)
            {
                ViewBag.favoritelist = db.personchannel.Where(x => x.FK_personid == Usr).Select(z => z.FK_channelid).ToList();
                return View(db.program.Include("channel").ToList());
            }
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public ActionResult chanlist()
        {
            ViewBag.addfavorite = db.channel.Select(f => new SelectListItem { Value = f.channelid.ToString(), Text = f.name });
            personchannel favorite = new personchannel();
            return View(favorite);
        }
        [HttpPost]
        public ActionResult chanlist(personchannel favorite)
        {
            var Usr = Convert.ToInt32(Session["id"]);
            try
            {
                personchannel newfavorite = new personchannel();
                newfavorite.FK_channelid = favorite.FK_channelid;
                newfavorite.FK_personid = Usr;
                db.personchannel.Add(newfavorite);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("MyPage", "Home");
        }

        public ActionResult addfavorite()
        {
            return View("chanlist");
        }
        [HttpGet]
        public ActionResult AdminPage()
        {
            ViewBag.programList = db.program.Select(f => new SelectListItem { Value = f.programid.ToString(), Text = f.name });
            news newNews = new news();
            return View(newNews);
        }
        [HttpPost]
        public ActionResult AdminPage(news newNews)
        {
            if (ModelState.IsValid)
            {
                news updatenews = new news();
                updatenews.programid = newNews.programid;
                updatenews.information = newNews.information;
                db.news.Add(updatenews);
                db.SaveChanges();
            }
            ModelState.Clear();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult newsinfo(int Id)
        {
            List<program> news = db.program.Where(s => s.programid == Id).ToList();
            return View(news);
        }

        [HttpGet]
        public ActionResult channelinfo(int cID)
        {
            List<program> prog = db.program.Where(p => p.FK_channelid == cID).ToList();
            return View(prog);
        }

    }
}

MVCGruppuppgift/MVCGruppuppgift/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCGruppuppgift.Models;

namespace MVCGruppuppgift.Controllers
{
    public class newsController : Controller
    {
        tvdbEntities db = new tvdbEntities();

        // GET: news
        public ActionResult Index()
        {
            var news = db.news.Include(n => n.program);
            return View(news.ToList());
        }

        // GET: news/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: news/Create
        public ActionResult Create()
        {
            ViewBag.programid = new SelectList(db.program, "programid", "name");
            return View();
        }

        // POST: news/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,programid,information")] news news)
        {
            if (ModelState.IsValid)
            {
                db.news.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.programid = new SelectList(db.program, "programid", "name", news.programid);
            return View(news);
        }

        // GET: news/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.programid = new SelectList(db.program, "programid", "name", news.programid);
            return View(news);
        }

        // POST: news/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,programid,information")] news news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.programid = new SelectList(db.program, "programid", "name", news.programid);
            return View(news);
        }

        // GET: news/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: news/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            news news = db.news.Find(id);
            db.news.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCGruppuppgift/MVCGruppuppgift/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCGruppuppgift/MVCGruppuppgift/Views/Home/AdminPage.cshtml
@model MVCGruppuppgift.Models.news
@{
    ViewBag.Title = "Adminpage";
}
@*Sida för att hantera nyhetspuffar*@

<div id="adminNewsSection">
    <h3>Lägga till nyheter:</h3>
    @*lägga till nyhetspuffar*@
    @using (Html.BeginForm("AdminPage", "Home", FormMethod.Post))
    {
        @Html.LabelFor(model => model.programid)<br />
        @Html.DropDownListFor(x => x.programid, new SelectList(ViewBag.programList, "Value", "Text"))<br />
        <br />
        @Html.LabelFor(model => model.information)<br />
        @Html.TextAreaFor(model => model.information)<br /><br />

        <input class="btn btn-primary" type="submit" id="btnadminPage" value="Lägg till" />
    }    
        <div>
            <hr>
            @*Redigera nyhetspuffar*@
            <h3>Redigera och ta bort aktiva puffar</h3>
            <br />
            <input class="btn btn-primary" type="button" value="Redigera puffar" onclick="location.href='@Url.Action("Index", "news")'" />
        </div>
</div>

MVCGruppuppgift/MVCGruppuppgift/Views/Home/MyPage.cshtml
@model IEnumerable<MVCGruppuppgift.Models.program>
@{
    ViewBag.Title = "Min Sida";
}
<div class="addChannel">
    <input class="btn btn-primary" id="favoriteChannelButton" type="button" value="Lägg till favorit kanal" onclick="location.href='@Url.Action("chanlist", "Home")'" />

</div>
<div class="favoriteChannels">
    @foreach (int channel in ViewBag.favoritelist)
    {
    <div class="channel">

    @if (channel == 1)
    {
        <h3 class="channels">SVT1</h3>        
    }
    else if (channel == 2)
    {
        <h3 class="channels">SVT2</h3>
    }
        else if (channel == 3)
    {
         <h3 class="channels">TV3</h3>
     }
     else if (channel == 4)
     {
     <h3 class="channels">TV4</h3>
    }
    else if (channel == 5)
    {
        <h3 class="channels">TV6</h3>        
    }
        @foreach (var program in Model)
        {
            if (channel == program.FK_channelid)
            {

            <ul class="programs list-unstyled row">
                <li>
                    <b><a>@program.time_from @program.name</a></b>
                </li>

            </ul>

    }
}



    </div>

    }
</div>

MVCGruppuppgift/MVCGruppuppgift/Views/Home/chanlist.cshtml
@model MVCGruppuppgift.Models.personchannel

    @*Lägga till nya kanaler i sin egna lista*@
<div id="addFavoriteSection">
    @using (Html.BeginForm("chanlist", "Home", FormMethod.Post))
    {

        @Html.DropDownListFor(x => x.FK_channelid, new SelectList(ViewBag.addfavorite, "Value", "Text"))


        <input type="submit" value="Lägg till" id="addchannels" />
    }
</div>

MVCGruppuppgift/MVCGruppuppgift/Views/Home/channelinfo.cshtml
@model IEnumerable<MVCGruppuppgift.Models.program>

@{
    ViewBag.Title = "newsinfo";
}
@{
    var kanal = "";
}
@foreach (var i in Model)
{
    if (i.FK_channelid == 1)
    {
        kanal = "SVT1";
    }
    else if (i.FK_channelid == 2)
    {
        kanal = "SVT2";
    }
    else if (i.FK_channelid == 3)
    {
        kanal = "TV3";
    }
    else if (i.FK_channelid == 4)
    {
        kanal = "TV4";
    }
    else if (i.FK_channelid == 5)
    {
        kanal = "TV6";
    }
}
<div class="col-12" id="selectChannelInfo">

    <h1>@kanal</h1>
    <ul class="list-unstyled">

        @foreach (var item in Model)
        {
        <li>
            @item.date.Value.ToString("yyyy-MM-dd"),
            @item.time_from.Value.ToString(@"hh\:mm"),
            @item.name
        </li>
            <li>                
                @item.description
            </li>
        }
        </ul>

</div>

MVCGruppuppgift/MVCGruppuppgift/Views/Home/newsinfo.cshtml
@model IEnumerable<MVCGruppuppgift.Models.program>

@{
    ViewBag.Title = "newsinfo";
}

@{var kanal = ""; }
@{ var kanalinfo = new HtmlString("Programmet visas på"); }

<div id="newsInfoSection">
    @foreach (var item in Model)
    {
        if (item.FK_channelid == 1)
        {
            kanal = "SVT1";
        }
        else if (item.FK_channelid == 2)
        {
            kanal = "SVT2";
        }
        else if (item.FK_channelid == 3)
        {
            kanal = "TV3";
        }
        else if (item.FK_channelid == 4)
        {
            kanal = "TV4";
        }
        else if (item.FK_channelid == 5)
        {
            kanal = "TV6";
        }
        <div>
            <p>
                <h2>Information om programmet</h2>
                <hr />
                <h2><u>@item.name</u></h2>
            <h4>@item.description, Visas på: @kanal</h4>
                @item.date.Value.ToString("yyyy-MM-dd")
                Kl. @item.time_from
            </p>
        </div>
    }
    @Html.ActionLink("Tillbaka", "Index", "Home", null, new { @class = "btn btn-primary btn-large" })
</div>