MVCGruppuppgift/MVCGruppuppgift/Controllers/personController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCGruppuppgift.Models;

namespace MVCGruppuppgift.Controllers
{
   
    public class personController : Controller
    {
        //detta är våran person controller där vi lägger in datan som ska vara kopplad till inlogging,redigering
        // och de personliga inställningarna
        tvdbEntities db = new tvdbEntities();


        // GET: person
        public ActionResult Index()
        {
            return View(db.person.ToList());
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(person reg)
        {
            if (ModelState.IsValid)
            {
                db.person.Add(reg);
                db.SaveChanges();
                return RedirectToAction("Login", "Login");
            }
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Welcome()
        {
            return View();
        }

        // GET: person/Details/5
        //Metod som tar ett ID från dbn. Den kopplar till en view med autogenererad kod.YOLO
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            person person = db.person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: person/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "personid,name,email,password,role,SVT1,SVT2,TV3,TV4,TV6")] person person)
        {
            if (ModelState.IsValid)
            {
                db.person.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: person/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            person person = db.person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: person/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "personid,name,email,password,role,SVT1,SVT2,TV3,TV4,TV6")] person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: person/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            person person = db.person.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            person person = db.person.Find(id);
            db.person.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCGruppuppgift/MVCGruppuppgift/Views/Shared/_Footer.cshtml
@*Partial view som renderas i layout for footer*@
<footer id="main-footer">
    <div class="container" id="footerTop">
        <div class="row text-center">
            @*Div med all kontaktinfo*@
            <div class="col-md-4 text-center">
                <h4>Kontakt</h4>
                <hr />
                <ul class="list-unstyled">
                    <li>Adress : Stureplanshänget 123</li>
                    <li>Telefon: 07013371337</li>
                    <li>E-post: HardcoreTV@gmail.com</li>
                </ul>
            </div>
            @*Div med social media ikoner*@
            <div class="col-md-4 social-media-links text-center text-white">
                <h4>Våra Sociala Medier</h4>
                <hr />
                <a id="facebook" href="https://www.facebook.com" target="_blank" title="Facebook"><i class="fab fa-facebook fa-2x"></i></a>
                <a id="youtube" href="https://www.youtube.com" target="_blank" title="Youtube"><i class="fab fa-youtube fa-2x"></i></a>
                <a id="twitter" href="https://www.twitter.com" target="_blank" title="Twitter"><i class="fab fa-twitter-square fa-2x"></i></a>
            </div>
            @*Lite info om harcoreTV*@
            <div class="col-md-4 text-center">
                <h4>Om Oss</h4>
                <hr />
                <ul class="list-unstyled">
                    <li>Hardcoretv.se är Sveriges bästa tablå</li>
                    <li>Vi siktar på att bli de bästa inom tablå verksamheten!</li>
                </ul>
            </div>
        </div>
    </div>
    @*en till separat footer som lägger sig längs ner med datum*@
    <div class="footer-bottom">
        <div class="container">
            <p>©@DateTime.Now.Year - Hardcore TV</p>
        </div>
    </div>
</footer>

MVCGruppuppgift/MVCGruppuppgift/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial scale=1.0">
    <title>@ViewBag.Title - Andreas & Erik MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*Link för Fontawesome ikoner*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    @*Läser in scripts länkade i bundles*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    @*Renderar navbaren från en partial view*@
    @Html.Partial("_NavBar")

    @*Renderar body beroende på sida man är inne på*@
    <div class="container body-content">
        @RenderBody()
    </div>

    @*Renderar footer från en partial view*@
    @Html.Partial("_Footer")
  
</body>
</html>

MVCGruppuppgift/MVCGruppuppgift/Views/Shared/_NavBar.cshtml
@*Partial view som renderas i layout för navbar*@
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    @*Ikon för hemsidan*@
    <div class="navbar-header vertical-line">
        <a title="Till startsidan" class="navbar-brand" href="@Url.Action("Index", "Home")">
            <span><img class="mr-2" height="50" width="50" src="~/img/icon.png" />Hardcore TV</span>
        </a>
    </div>
    @*Colapsing navbar med hamburgermeny*@
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            @*Ger vissa vissa länkar om man är inloggad och admin. Hem, Min sida, Adminsida som är för att redigera puggar och logga ut*@
            @if (Session["admin"] != null)
            {
                <li class="nav-item">
                    <a title="Hem" class="nav-link" href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i>Hem</a>
                </li>
                <li class="nav-item">
                    <a title="Min Sida" class="nav-link" href="@Url.Action("MyPage", "Home")"><i class="fas fa-newspaper"></i>Min Sida</a>
                </li>
                <li class="nav-item">
                    <a title="Redigera puffar" class="nav-link" href="@Url.Action("AdminPage", "Home")"><i class="far fa-edit"></i>Redigera puffar</a>
                </li>
                <li class="nav-item">
                    <a title="Logga ut" class="nav-link" href="@Url.Action("Logout", "Login")"><i class="fas fa-sign-in-alt"></i>Logga ut</a>
                </li>

            }
            @*Ger vissa länkar om man är inloggad användare. Hem, Min sida, och logga ut*@
            else if (Session["id"] != null)
            {
                <li class="nav-item">
                    <a title="Hem" class="nav-link" href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i>Hem</a>
                </li>
                <li class="nav-item">
                    <a title="Min Sida" class="nav-link" href="@Url.Action("MyPage", "Home")"><i class="fas fa-newspaper"></i>Min Sida</a>
                </li>
                <li class="nav-item">
                    <a title="Logga ut" class="nav-link" href="@Url.Action("Logout", "Login")"><i class="fas fa-sign-in-alt"></i>Logga ut</a>
                </li>
            }
            @*Om man inte är inloggad så får man vissa val. Hem, Registrera och Logga in*@
            else
            {
                <li class="nav-item">
                    <a title="Hem" class="nav-link" href="@Url.Action("Index", "Home")"><i class="fas fa-home"></i>Hem</a>
                </li>
                <li class="nav-item">
                    <a title="Registrera" class="nav-link" href="@Url.Action("Register", "person")"><i class="fas fa-pen"></i>Registrera</a>
                </li>
                <li class="nav-item">
                    <a title="Logga in" class="nav-link" href="@Url.Action("Login", "Login")"><i class="fas fa-sign-in-alt"></i>Logga in</a>
                </li>
            }
        </ul>        
    </div>
</nav>